version: '2'

services:
  ftp_server:
    image: delfer/alpine-ftp-server
    hostname: spectre-ftp
    ports:
      - '2121:21'
      - 21000-21010:21000-21010
    environment:
      - USERS=developer|dev
